openapi: 3.0.0
info:
  title: API de usuários
  version: 1.0.0
paths:
  /users:
    get:
      summary: Listar todos os usuários
      responses:
        '200':
          description: OK
    post:
      summary: Criar um novo usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - name
                - email
                - password
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  name:
                    type: string
                  email:
                    type: string
                    format: email
                  password:
                    type: string
  /users/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: ID do usuário
        schema:
          type: string
    get:
      summary: Detalhar um usuário
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  name:
                    type: string
                  email:
                    type: string
                    format: email
                  password:
                    type: string
        '404':
          description: Not Found
    put:
      summary: Atualizar um usuário
      parameters:
        - name: id
          in: path
          required: true
          description: ID do usuário
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - name
                - email
                - password
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
    delete:
      summary: Deletar um usuário
      parameters:
        - name: id
          in: path
          required: true
          description: ID do usuário
          schema:
            type: string
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
